### ISSUE TITLE
merge with alternative port

### ISSUE THREAD

**Issue by nivkner** [icefoxen/rinimp3#8]
hello @icefoxen,
I read your blog post when it appeared on Reddit a while back, and decided to also try to port minimp3.
The result is [here](https://github.com/nivkner/minimp3port).

I have no long term plans for maintaining it, since it was more of a learning experience. However, I saw your crate on [crates.io](https://crates.io/crates/rinimp3), so I decided to see if you want to merge our ports.

This isn't a pull request since the repositories don't share any common base, but I am willing to help if you need any.

**Comment by icefoxen** [comment]
Hey, nice work!  :D  Unfortunately I have no long term plans for maintaining this either, so I'm not sure that merging these would accomplish much.  Yours looks far more complete than mine anyway.
